In [122]:
import numpy as np
import pylab as pl
import warnings
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression


import pandas as pd


from scipy import linalg
from sklearn.datasets import load_digits
from sklearn.decomposition import TruncatedSVD
from sklearn.ensemble import RandomForestClassifier 
warnings.filterwarnings("ignore")

In [178]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler



Уровень 0:
Придумайте матрицы, которые обладают следующими свойствами:

 * Диагональная, ортогональная, но не единичная(!)

* Верхнетреугольная, ортогональная

* Нижнетреугольная, ортогональная

* Матрица, у которой определитель = 1, и все элементы не равны 0

 * Диагональная, ортогональная, но не единичная(!)

In [182]:
D = np.diag([1, -1, -1])
D

array([[ 1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

* Верхнетреугольная, ортогональная

In [188]:
m = np.triu([[-1, 0, 0], [0,1, 0], [0,0,-1]], -1)
m

array([[-1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

* Нижнетреугольная, ортогональная

In [192]:
m = np.tril(D, 0)
print(m)

[[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]


* Матрица, у которой определитель = 1, и все элементы не равны 0

In [9]:
m = np.array([[1, 1, 0], [2, 1, 6], [1, 1, 1]], dtype=np.float32)
det = np.linalg.det(m)
print(m)
print(det)

[[1. 1. 0.]
 [2. 1. 6.]
 [1. 1. 1.]]
-1.0


* Найдите собственные значения и собственные вектора матриц

X = S^T * D * S

In [11]:
m = np.array([[2, 2], [1, 3]])
m

array([[2, 2],
       [1, 3]])

In [12]:
w, v = np.linalg.eig(m)

In [64]:
for i in range(len(w)):
    print('Собственное значение ' + str(w[i]))
    print('Собственный вектор ' + str(v[:,i]))

Собственное значение 1.0
Собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
Собственный вектор [-0.70710678 -0.70710678]


Уровень 1:
Найдите спектральное разложение матрицы:

In [65]:
m = np.array([[1,2], [2,3]])
m

array([[1, 2],
       [2, 3]])

In [67]:
v, w = np.linalg.eigh(m) #находим собственные значения и вектора

In [77]:
D = np.diag(v) #диагональная матрица из собственных значений
D

array([[-0.23606798,  0.        ],
       [ 0.        ,  4.23606798]])

In [71]:
S = w.T   #матрица из собственных значений
S

array([[-0.85065081,  0.52573111],
       [ 0.52573111,  0.85065081]])

In [72]:
S.T   #транспонированая матрица S

array([[-0.85065081,  0.52573111],
       [ 0.52573111,  0.85065081]])

In [78]:
np.dot(S.T, S) # убедимся что матрица S и ST ортогональны

array([[1., 0.],
       [0., 1.]])

In [75]:
np.dot(np.dot(S.T, D),S) #Убедимся, что матрицы ST, S и D образуют спектральное разложение

array([[1., 2.],
       [2., 3.]])

In [26]:
#вариант из доп.материала
l = np.array([[1,2], [2,3]])

In [32]:
a, U = linalg.eig(l)
print('Eigenvalues:')
print(np.array(a, dtype=float))
print('\nEigenvectors:')
print(U)

Eigenvalues:
[-0.23606798  4.23606798]

Eigenvectors:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [33]:
print(np.array(U.dot(np.diag(a)).dot(U.T), dtype=float))

[[1. 2.]
 [2. 3.]]


 * SVD Разложение
 * исходная может быть не квадратной
 
 X = U * D * V


In [195]:
X = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

In [196]:
U, s, W = np.linalg.svd(X)

In [199]:
V = W.T

In [202]:
D = np.zeros_like(X, dtype=float)

In [204]:
D[np.diag_indices(min(X.shape))] = s
D

array([[8.82, 0.00, 0.00],
       [0.00, 6.14, 0.00],
       [0.00, 0.00, 2.53],
       [0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00]])

In [205]:
np.dot(U.T, U)

array([[1.00, -0.00, 0.00, 0.00, 0.00],
       [-0.00, 1.00, -0.00, -0.00, -0.00],
       [0.00, -0.00, 1.00, 0.00, -0.00],
       [0.00, -0.00, 0.00, 1.00, -0.00],
       [0.00, -0.00, -0.00, -0.00, 1.00]])

In [206]:
np.dot(V.T,V)

array([[1.00, 0.00, 0.00],
       [0.00, 1.00, 0.00],
       [0.00, 0.00, 1.00]])

In [207]:
np.dot(np.dot(U, D), V.T)

array([[1.00, 2.00, -0.00],
       [-0.00, 0.00, 5.00],
       [3.00, -4.00, 2.00],
       [1.00, 6.00, 5.00],
       [0.00, 1.00, 0.00]])